remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: Adam
description: User Guide for Adam - Your Personal Task Management ChatBot
show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
